// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Proxy struct {
	ID             int64
	Host           string
	Port           int64
	ProxyType      string
	Country        *string
	Anonymity      *string
	Https          *bool
	Status         string
	ResponseTimeMs *int64
	FailCount      *int64
	FirstSeenAt    time.Time
	LastCheckedAt  *time.Time
	LastHealthyAt  *time.Time
}
