// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"time"
)

const cleanupOldProxies = `-- name: CleanupOldProxies :exec
DELETE FROM proxies
WHERE last_healthy_at IS NULL OR last_healthy_at < ?
`

func (q *Queries) CleanupOldProxies(ctx context.Context, lastHealthyAt *time.Time) error {
	_, err := q.db.ExecContext(ctx, cleanupOldProxies, lastHealthyAt)
	return err
}

const countHealthyProxies = `-- name: CountHealthyProxies :one
SELECT COUNT(*) FROM proxies WHERE status = 'healthy'
`

func (q *Queries) CountHealthyProxies(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countHealthyProxies)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProxies = `-- name: CountProxies :one
SELECT COUNT(*) FROM proxies
`

func (q *Queries) CountProxies(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProxies)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProxiesByType = `-- name: CountProxiesByType :many
SELECT proxy_type, COUNT(*) AS count FROM proxies GROUP BY proxy_type
`

type CountProxiesByTypeRow struct {
	ProxyType string
	Count     int64
}

func (q *Queries) CountProxiesByType(ctx context.Context) ([]CountProxiesByTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, countProxiesByType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountProxiesByTypeRow
	for rows.Next() {
		var i CountProxiesByTypeRow
		if err := rows.Scan(&i.ProxyType, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHealthyProxies = `-- name: GetHealthyProxies :many
SELECT id, host, port, proxy_type, country, anonymity, https, status, response_time_ms, fail_count, first_seen_at, last_checked_at, last_healthy_at FROM proxies
WHERE status = 'healthy'
ORDER BY last_healthy_at DESC
`

func (q *Queries) GetHealthyProxies(ctx context.Context) ([]Proxy, error) {
	rows, err := q.db.QueryContext(ctx, getHealthyProxies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Proxy
	for rows.Next() {
		var i Proxy
		if err := rows.Scan(
			&i.ID,
			&i.Host,
			&i.Port,
			&i.ProxyType,
			&i.Country,
			&i.Anonymity,
			&i.Https,
			&i.Status,
			&i.ResponseTimeMs,
			&i.FailCount,
			&i.FirstSeenAt,
			&i.LastCheckedAt,
			&i.LastHealthyAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProxyByHostPort = `-- name: GetProxyByHostPort :one
SELECT id, host, port, proxy_type, country, anonymity, https, status, response_time_ms, fail_count, first_seen_at, last_checked_at, last_healthy_at FROM proxies
WHERE host = ? AND port = ?
`

type GetProxyByHostPortParams struct {
	Host string
	Port int64
}

func (q *Queries) GetProxyByHostPort(ctx context.Context, arg GetProxyByHostPortParams) (Proxy, error) {
	row := q.db.QueryRowContext(ctx, getProxyByHostPort, arg.Host, arg.Port)
	var i Proxy
	err := row.Scan(
		&i.ID,
		&i.Host,
		&i.Port,
		&i.ProxyType,
		&i.Country,
		&i.Anonymity,
		&i.Https,
		&i.Status,
		&i.ResponseTimeMs,
		&i.FailCount,
		&i.FirstSeenAt,
		&i.LastCheckedAt,
		&i.LastHealthyAt,
	)
	return i, err
}

const markProxyHealthy = `-- name: MarkProxyHealthy :exec
UPDATE proxies
SET status = ?, last_checked_at = CURRENT_TIMESTAMP, response_time_ms = ?,
    last_healthy_at = CURRENT_TIMESTAMP, fail_count = 0
WHERE id = ?
`

type MarkProxyHealthyParams struct {
	Status         string
	ResponseTimeMs *int64
	ID             int64
}

func (q *Queries) MarkProxyHealthy(ctx context.Context, arg MarkProxyHealthyParams) error {
	_, err := q.db.ExecContext(ctx, markProxyHealthy, arg.Status, arg.ResponseTimeMs, arg.ID)
	return err
}

const markProxyUnhealthy = `-- name: MarkProxyUnhealthy :exec
UPDATE proxies
SET status = ?, last_checked_at = CURRENT_TIMESTAMP, response_time_ms = ?,
    fail_count = fail_count + 1
WHERE id = ?
`

type MarkProxyUnhealthyParams struct {
	Status         string
	ResponseTimeMs *int64
	ID             int64
}

func (q *Queries) MarkProxyUnhealthy(ctx context.Context, arg MarkProxyUnhealthyParams) error {
	_, err := q.db.ExecContext(ctx, markProxyUnhealthy, arg.Status, arg.ResponseTimeMs, arg.ID)
	return err
}

const upsertProxy = `-- name: UpsertProxy :one
INSERT INTO proxies (host, port, proxy_type, country, first_seen_at)
VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(host, port) DO UPDATE SET
    proxy_type = excluded.proxy_type,
    country = excluded.country
RETURNING id, host, port, proxy_type, country, anonymity, https, status, response_time_ms, fail_count, first_seen_at, last_checked_at, last_healthy_at
`

type UpsertProxyParams struct {
	Host      string
	Port      int64
	ProxyType string
	Country   *string
}

func (q *Queries) UpsertProxy(ctx context.Context, arg UpsertProxyParams) (Proxy, error) {
	row := q.db.QueryRowContext(ctx, upsertProxy,
		arg.Host,
		arg.Port,
		arg.ProxyType,
		arg.Country,
	)
	var i Proxy
	err := row.Scan(
		&i.ID,
		&i.Host,
		&i.Port,
		&i.ProxyType,
		&i.Country,
		&i.Anonymity,
		&i.Https,
		&i.Status,
		&i.ResponseTimeMs,
		&i.FailCount,
		&i.FirstSeenAt,
		&i.LastCheckedAt,
		&i.LastHealthyAt,
	)
	return i, err
}
