//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Proxies struct {
	ID             *int32 `sql:"primary_key"`
	Host           string
	Port           int32
	ProxyType      string
	Country        *string
	Anonymity      *string
	HTTPS          *bool
	Status         string
	ResponseTimeMs *int32
	FailCount      *int32
	FirstSeenAt    time.Time
	LastCheckedAt  *time.Time
	LastHealthyAt  *time.Time
}
